# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s1545317/DL4/IR_interface/IR_interface.cache/wt [current_project]
set_property parent.project_path /home/s1545317/DL4/IR_interface/IR_interface.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/s1545317/DL4/IR_interface/IR_interface.srcs/sources_1/new/Generic_counter.v
  /home/s1545317/DL4/IR_interface/IR_interface.srcs/sources_1/new/IR_Transmitter_SM.v
}
read_xdc /home/s1545317/DL4/IR_interface/IR_interface.srcs/constrs_1/new/IR_constraints.xdc
set_property used_in_implementation false [get_files /home/s1545317/DL4/IR_interface/IR_interface.srcs/constrs_1/new/IR_constraints.xdc]

synth_design -top IR_Transmitter_SM -part xc7a35tcpg236-1
write_checkpoint -noxdef IR_Transmitter_SM.dcp
catch { report_utilization -file IR_Transmitter_SM_utilization_synth.rpt -pb IR_Transmitter_SM_utilization_synth.pb }
